# Site settings
title: Biblioteca virtual do CALICO
tag_text: Biblioteca virtual do CALICO
description: Biblioteca virtual do CALICO

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
